// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	dto "ropc-service/model/dto"
	entities "ropc-service/model/entities"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticatorContract is an autogenerated mock type for the AuthenticatorContract type
type AuthenticatorContract struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: user, client
func (_m *AuthenticatorContract) Authenticate(user *entities.User, client *entities.Client) (*dto.Token, error) {
	ret := _m.Called(user, client)

	var r0 *dto.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.User, *entities.Client) (*dto.Token, error)); ok {
		return rf(user, client)
	}
	if rf, ok := ret.Get(0).(func(*entities.User, *entities.Client) *dto.Token); ok {
		r0 = rf(user, client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.User, *entities.Client) error); ok {
		r1 = rf(user, client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthenticatorContract interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticatorContract creates a new instance of AuthenticatorContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticatorContract(t mockConstructorTestingTNewAuthenticatorContract) *AuthenticatorContract {
	mock := &AuthenticatorContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
