// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GrantType is an autogenerated mock type for the GrantType type
type GrantType struct {
	mock.Mock
}

type mockConstructorTestingTNewGrantType interface {
	mock.TestingT
	Cleanup(func())
}

// NewGrantType creates a new instance of GrantType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGrantType(t mockConstructorTestingTNewGrantType) *GrantType {
	mock := &GrantType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
