// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Oauth2 is an autogenerated mock type for the Oauth2 type
type Oauth2 struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: grantType
func (_m *Oauth2) Authenticate(grantType string) {
	_m.Called(grantType)
}

type mockConstructorTestingTNewOauth2 interface {
	mock.TestingT
	Cleanup(func())
}

// NewOauth2 creates a new instance of Oauth2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOauth2(t mockConstructorTestingTNewOauth2) *Oauth2 {
	mock := &Oauth2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
