// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "ropc-service/model/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserAuthenticator is an autogenerated mock type for the UserAuthenticator type
type UserAuthenticator struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: username, password
func (_m *UserAuthenticator) Authenticate(username string, password string) (*entities.User, error) {
	ret := _m.Called(username, password)

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*entities.User, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *entities.User); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserAuthenticator interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserAuthenticator creates a new instance of UserAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserAuthenticator(t mockConstructorTestingTNewUserAuthenticator) *UserAuthenticator {
	mock := &UserAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
