// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "ropc-service/model/entities"

	mock "github.com/stretchr/testify/mock"
)

// ClientRepository is an autogenerated mock type for the ClientRepository type
type ClientRepository struct {
	mock.Mock
}

// GetClient provides a mock function with given fields: clientId
func (_m *ClientRepository) GetClient(clientId string) (*model.Client, error) {
	ret := _m.Called(clientId)

	var r0 *model.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Client, error)); ok {
		return rf(clientId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Client); ok {
		r0 = rf(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClientRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewClientRepository creates a new instance of ClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientRepository(t mockConstructorTestingTNewClientRepository) *ClientRepository {
	mock := &ClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
