// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "ropc-service/model"

	mock "github.com/stretchr/testify/mock"
)

// ClientAuthenticatorContract is an autogenerated mock type for the ClientAuthenticatorContract type
type ClientAuthenticatorContract struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: clientId, clientSecret
func (_m *ClientAuthenticatorContract) Authenticate(clientId string, clientSecret string) (*model.Client, error) {
	ret := _m.Called(clientId, clientSecret)

	var r0 *model.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.Client, error)); ok {
		return rf(clientId, clientSecret)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.Client); ok {
		r0 = rf(clientId, clientSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientId, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClientAuthenticatorContract interface {
	mock.TestingT
	Cleanup(func())
}

// NewClientAuthenticatorContract creates a new instance of ClientAuthenticatorContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientAuthenticatorContract(t mockConstructorTestingTNewClientAuthenticatorContract) *ClientAuthenticatorContract {
	mock := &ClientAuthenticatorContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
