// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ThirdPartyClientAuthenticator is an autogenerated mock type for the ThirdPartyClientAuthenticator type
type ThirdPartyClientAuthenticator struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: clientID, clientSecret
func (_m *ThirdPartyClientAuthenticator) Authenticate(clientID string, clientSecret string) (bool, error) {
	ret := _m.Called(clientID, clientSecret)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(clientID, clientSecret)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(clientID, clientSecret)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientID, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewThirdPartyClientAuthenticator interface {
	mock.TestingT
	Cleanup(func())
}

// NewThirdPartyClientAuthenticator creates a new instance of ThirdPartyClientAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewThirdPartyClientAuthenticator(t mockConstructorTestingTNewThirdPartyClientAuthenticator) *ThirdPartyClientAuthenticator {
	mock := &ThirdPartyClientAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
