// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "ropc-service/model"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: username
func (_m *UserRepository) GetUser(username string) (*model.User, error) {
	ret := _m.Called(username)

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAndClient provides a mock function with given fields: user, client
func (_m *UserRepository) GetUserAndClient(user *model.User, client *model.Client) (*model.User, error) {
	ret := _m.Called(user, client)

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.User, *model.Client) (*model.User, error)); ok {
		return rf(user, client)
	}
	if rf, ok := ret.Get(0).(func(*model.User, *model.Client) *model.User); ok {
		r0 = rf(user, client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User, *model.Client) error); ok {
		r1 = rf(user, client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
