apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ropc-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/unitz007/ropc-backend.git
    targetRevision: HEAD
    path: ops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd